### ISSUE TITLE
将华农宝除课表外所有模块用 HTML 5 实现

### ISSUE THREAD

**Issue by SpecialCyCi** [iSCAU/iSCAU-Android#13]
今年 9 月份开学前实现。

**Comment by haosdent** [comment]
为啥要怎么搞了

**Comment by SpecialCyCi** [comment]
同时维护两个版本，在有成员已经毕业情况下，确实难以维护。

**Comment by haosdent** [comment]
哦，不容易啊，现在有没有华农宝有没有收入或者捐献啥的啊。

**Comment by SpecialCyCi** [comment]
没有.. 靠捐献也不靠谱，用户也就是大学生...

**Comment by haosdent** [comment]
呃，这个还是交给你的师弟们去干吧，然后这种应该开个新项目，然后在github建个里程碑，分成更多issues。

**Comment by SpecialCyCi** [comment]
还没想好详细，建个 ISSUE 提醒下自己。事儿多了，有些东西就忘掉了。

**Comment by 691152552** [comment]
致华农宝团队负责人：  
   本团队主要由华南农业大学12工程学院电气专业学生组成。
最近因参加创业基金会被几位投资人看好我们的想法，明确在成功推广后投以我们基金作为种子资本。
   虽然我们仍然处于起步阶段，但是我们的想法得到他们的主动关注与厚重期望。
如今我们团队因招募人员遇到困难，望得到你们的技术支持，进而商讨推广模式、盈利模式。
   我们更希望与你们成为合伙人，把软件推向全省乃至全国。
具体合作细节请联系     QQ：691152552
   O(∩_∩)O谢谢         期待你的回复！                                                                                                                                                                                                                                              渡渡创业团队

**Comment by SpecialCyCi** [comment]
丢了两年的 issues......
