### ISSUE TITLE
华农宝开发童鞋可以申请下Github Education

### ISSUE THREAD

**Issue by haosdent** [iSCAU/iSCAU-Android#18]
https://education.github.com/pack 用学校的学生电子邮箱就可以申请，包括可以在Github上创建私有仓库（用户或组织都可以）Travis和Digital一定额度内免费等优惠措施。记得在Plan里面描述清楚要做的事。

**Comment by SilverRainZ** [comment]
GitHub Education 真是良心.

**Comment by SpecialCyCi** [comment]
@xillkey 老板，去弄个呢。

**Comment by haosdent** [comment]
送了一个.me 的域名
送了5个私有库
送了100美元的digitalocean代金券，可以买20个月的服务器
送了travis build私有库的权限
其他好像还有一些乱七八糟的。

On Sat, Oct 18, 2014 at 1:48 PM, Specyci notifications@github.com wrote:

> @xillkey https://github.com/xillkey 老板，去弄个呢。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/iSCAU/iSCAU-Android/issues/18#issuecomment-59600230.

## 

Best Regards,
Haosdent Huang

**Comment by SpecialCyCi** [comment]
老板们应该申请了（我自己也弄了一个...
关了。
